
spring:
  application:
    name: product
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}



  #配置mq test
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

